export const getRouteProductsPage = () => `/products`;
export const getRouteProductPage = (id: number | string) => `/products/${id}`;
export const getRouteLoginPage = (from: string = '') => from ? `/auth/login?from=${from}` : `/auth/login`;
export const getRouteLogoutPage = (from: string = '') => from ? `/auth/logout?from=${from}` : `/auth/logout`;
export const getRouteSignupPage = () => `/auth/signup`;
export const getRouteAdminPage = () => `/admin`;
export const getRouteCartPage = () => `/cart`; 
export const getRouteCheckoutPage = () => `/checkout`;
export const getRouteCheckoutDeliveryAddressPage = () => `/checkout/deliveryAddress`;
export const getRouteCheckoutPaymentTypePage = () => `/checkout/paymentType`;
export const getRouteCheckoutOrderReviewPage = () => `/checkout/orderReview`;
export const getRouteCheckoutPaymentPage = () => `/checkout/payment`;
export const getRouteCheckoutSuccessPage = (orderId: string) => `/checkout/successScreen?orderId=${orderId}`;
export const getRouteOrderPage = (id: number | string) => `/orders/${id}`;
export const getRouteOrdersPage = () => `/orders`;
export const getRouteManagerOrdersPage = () => `/manager/orders`;
